[package]
name = "windivert-sys"
version = "0.5.0"
description = "Raw FFI bindings for WinDivert user mode library"
authors = ["Ruben Serrano Izquierdo <rserranoizq@gmail.com>"]
repository = "https://github.com/Rubensei/windivert-rust.git"
homepage = "https://github.com/Rubensei/windivert-rust"
keywords = ["ffi", "windivert", "bindings", "driver"]
categories = ["external-ffi-bindings"]
readme = "../README.md"
license = "GPL-3.0-or-later"
edition = "2018"
links = "WinDivert"
build = "build.rs"

[lib]
name = "windivert_sys"

[dependencies]
byteorder = "1.4.2"
winapi = {version = "0.3.9", features = ["minwinbase", "minwindef", "ntdef"]}

[build-dependencies]
cc = "1.0.66"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"