[package]
name = "windivert"
version = "0.1.0"
description = "Wrapper library around windivert-sys"
authors = ["Ruben Serrano Izquierdo <rserranoizq@gmail.com>"]
repository = "https://github.com/Rubensei/windivert-rust.git"
homepage = "https://github.com/Rubensei/windivert-rust"
keywords = ["ffi", "windivert", "bindings", "driver"]
categories = ["external-ffi-bindings"]
readme = "../README.md"
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
etherparse = "0.9.0"
winapi = {version = "0.3.9", features = [
	"std",
	"ioapiset",
	"handleapi",
	"processthreadsapi",
	"synchapi",
	"winbase",
	"winerror",
	"winioctl",
	"winsvc"
]}
windivert-sys = { path = "../windivert-sys" }
