[package]
name = "windivert"
version = "0.2.0"
description = "Wrapper library around windivert-sys"
authors = ["Ruben Serrano Izquierdo <rserranoizq@gmail.com>"]
repository = "https://github.com/Rubensei/windivert-rust.git"
homepage = "https://github.com/Rubensei/windivert-rust"
keywords = ["ffi", "windivert", "bindings", "driver"]
categories = ["external-ffi-bindings"]
readme = "../README.md"
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
etherparse = "0.9.0"
windows = "0.17.2"
windivert-sys = { version = "0.6.0", path = "../windivert-sys" }

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"