[package]
name = "windivert"
version = "0.1.0"
authors = ["Ruben Serrano Izquierdo <rserranoizq@gmail.com>"]
edition = "2018"

[dependencies]
etherparse = "0.9.0"
winapi = {version = "0.3.9", features = [
	"std",
	"ioapiset",
	"handleapi",
	"processthreadsapi",
	"synchapi",
	"winbase",
	"winerror",
	"winioctl",
	"winsvc"
]}
windivert-sys = { path = "../windivert-sys" }
