permissions:
  contents: read
on:
  push:
    branches: [master, ci-tests]
  pull_request:
    branches: [master]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name || github.run_id }}
  cancel-in-progress: true
name: build
jobs:
  build:
    runs-on: windows-latest
    name: ${{matrix.feature}} / ${{ matrix.compiler }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc, gnu]
        feature: [vendored, static]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-${{ matrix.compiler }}
      - name: cargo build
        run: cargo build --target x86_64-pc-windows-${{ matrix.compiler }} --features ${{ matrix.feature }}
